.TH "int23_t.cpp" 3 "INT23_t" \" -*- nroff -*-
.ad l
.nh
.SH NAME
int23_t.cpp \- Main implementation file of int23_t library\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <bitset>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <type_traits>\fP
.br
\fC#include 'int23_t\&.hpp'\fP
.br

.SH "Detailed Description"
.PP 
Main implementation file of int23_t library\&. 

Contains implementation of functions required to make int23_t work 
.SH "Author"
.PP 
Generated automatically by Doxygen for INT23_t from the source code\&.
